// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7uB7hTr2W4Ke_nDCgRS4HxC1eMMQX3Hw',
    appId: '1:14976270990:web:b45235e9a43e2dcec77fdf',
    messagingSenderId: '14976270990',
    projectId: 'asynconf-tuto-pour-apprflutter',
    authDomain: 'asynconf-tuto-pour-apprflutter.firebaseapp.com',
    storageBucket: 'asynconf-tuto-pour-apprflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcjgXSqZgBRwx2u0rryEykiY1DhJZt2Qo',
    appId: '1:14976270990:android:31cacc3a4530ba84c77fdf',
    messagingSenderId: '14976270990',
    projectId: 'asynconf-tuto-pour-apprflutter',
    storageBucket: 'asynconf-tuto-pour-apprflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPmaiSsUoNCJYC4Wwz7PxTmYq4qKixhZc',
    appId: '1:14976270990:ios:8f946fe311a2d62bc77fdf',
    messagingSenderId: '14976270990',
    projectId: 'asynconf-tuto-pour-apprflutter',
    storageBucket: 'asynconf-tuto-pour-apprflutter.appspot.com',
    iosBundleId: 'fr.asynconftuto.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPmaiSsUoNCJYC4Wwz7PxTmYq4qKixhZc',
    appId: '1:14976270990:ios:9f0c68310e91b02bc77fdf',
    messagingSenderId: '14976270990',
    projectId: 'asynconf-tuto-pour-apprflutter',
    storageBucket: 'asynconf-tuto-pour-apprflutter.appspot.com',
    iosBundleId: 'fr.asynconftuto.flutterProjects.RunnerTests',
  );
}
